stanford-cs336/assignment1-basics-leaderboard

README.md

Trained in BF16, increased number of layers, increased context length, added weight tying

Leaderboard entry

---

README.md

compile, AMP, deeper wider architecture, gradient accumulation, context length 512

stephen submission

---

README.md

same wandb report; amp/matmul precision

new submission

---

README.md

Add Josh's leaderboard results

Update README.md with Josh's results

---

README.md

torch.compile, mixed precision, weight tying, bigger model

add chenchen's submission

---

README.md

Baseline implementation. Nothing else.

Leaderboard submission (@vprateek)

---

README.md

Hyperparameter tuning, used torch.compile, mixed precision, no checkpointing and reduced logging

Leaderboard submission

---

README.md

compile, add layers, increase context length, tune learning rate

Puheng Li's submission to leaderboard

---

README.md

Will add details about my implementation later:))

add herman

---

README.md

muon and torch compile and different lr for different parts of adamw. big and wide model

found better loss

---

README.md

Compiled model, mixed precision forward pass with torch.amp.autocast to bfloat16.
I pushed num_layers to 16, d_model -> 768, d_ff -> 2048.
Learning rate range of [1e-6, 1e-3] starting at 1e-5, warming up over 3000 steps and then cooling down to 1e-6 until either 30000 steps have been achieved or the cluster runs out of time (which is what happened).
Batch size 64, weight decay of 0.001, other AdamW parameters set to default.
Tried to do experiment of d_model -> 1024, d_ff -> 2752, but this wouldn't cooperate due to some environment issue.

Adam Zhao leaderboard submission

---

README.md

compile, larger model, mix precision

val result

---

README.md

standard implementation + slight tuning amount of data / model size

initial entry ken liu

---

README.md

final validation loss of 3.55
https://api.wandb.ai/links/sallyzhu-stanford-university/s6sd95zh
I used a Transformer with d_model = 768 (d_ff = 2048), and 5 layers, and context length of 512. I used a learning rate schedule with a min learning rate of 1e-3 and a max learning rate of 1e-4.

sally zhu leaderboard submission

---

README.md

Took the basic model we trained for OWT and let it run for longer. Achieved best validation loss of 3.85. (Intend to update this with a better performing model)
https://api.wandb.ai/links/dh2shin2-stanford-university/pfknvdyd
5113 seconds wallclock time = 85 minutes.

Add to leaderboard

---

README.md

Final validation loss: 3.99
Weights and Biases link: [https://api.wandb.ai/links/jayshenoy-stanford-university/shpznb3o](https://api.wandb.ai/links/jayshenoy-stanford-university/shpznb3o)
To achieve this loss, I modified the base model from the assignment by training with a batch size of 256.

Add Jay's training result

---

README.md

from initial: "compile, AMP, deeper wider architecture, gradient accumulation, context length 512"
+weight tying, muon optimizer, small model config/hyperparameter tweaks

stephen second submission

---

README.md

125M model trained for 30K steps. 350 warmup steps + 30000 decay steps with lr 3e-3.

arnuv leaderboard

---

README.md

Add Harshit based on https://wandb.ai/josharshit-stanford-university/cs336-basics/reports/CS-336--VmlldzoxMjM2NDcxMQ?accessToken=26yom3e3gznkpvg2yjispit1vhf4thw15i3xbj4hfckynojj0vc2g96bo7uedqec
Basic implementation.

Add Harshit to leaderboard

---

README.md

Added my leaderboard submission. I scaled up the model to use 6 layers + 768 d_model + 24 heads + 2048 d_ff with a context length of 512.

Add Karthik Dharmarajan

---

README.md

High-level: Muon Optimizer, bfloat16 training, deeper model, weight tying
For architectural changes, I implemented weight-tying, so that the learned parameters for embeddings and outprojections were the same. I also implemented the Muon Optimizer, which is an SGD-momentum optimizer that orthogonalizes the updates to the weight matrices. I also played with model size and learning rate throughout my runs. I found a sweetspot where my model size, in number of parameters, was 5\% of my total tokens processed. This follows the compute-optimal ratio found in DeepMind's Chinchilla paper. Lastly, I converted training to bfloat16 to save memory and allow for a larger model/batch size. Below are all of my runs, at the time of submitting this writeup:

Milan Rohatgi leaderboard submission

---

README.md

torch.compile, mixed precision, wider network (d_models=768, d_ff=2048), lr searching

Ziqing Huang submission

---

README.md

For this run, I implemented QK-norm, where we apply RMS norm to the Q and K before running attention. I also implemented weight-tying. Finally, I added a standard Mixture of Experts (MoE) design with 4 experts per block, with each pass taking weights from the top 2 experts. I also did some hyper-parameter tuning on the learning rate, and changed the angle for RoPE embeddings to 500000.

Justin Wu submission

---

README.md

Thanks course staff for making working on this assignment smooth and engaging!

Katherine Li submission

---

README.md

ayush leaderboard submit

---

README.md

What I did:
- AMP
- ReLU<sup>2</sup>
- `torch.compile`
- Muon (no warmup)
- Tanh logit softcapping
- Undertrained a large model
- RMSNorm after token embedding
- Initialize FFN and MHA output projections to zero
- Value residuals with learnable weights in attention blocks
- Weight tying (+ reduced variance for embedding initializations)
- Weighted shortcut from embedding output to every subsequent layer
Other things I experimented with:
- SwiGLU/SiLU
- Chinchilla optimal token:param ratio
- Various LR schedules (trapezoidal, flat-cosine, flat-linear, etc.)
- Untying embeddings and using multiple optimizer groups with different LRs
- Tinkering with weight decay, betas, Muon momentum warmup, and other hyperparams
- Context length schedule (128 -> 256 -> 512) and batch size schedule …

Brandon Snider — Leaderboard Submission

---

README.md

Used 16 layers, 8 heads, 1024 d_model, 512 seq len, 128 batch size, and ran for around 20k iters. Muon for everything except embedding, lm head and 1-dimensional values. Different weights for muon, embedding, lm head and scalar values.
I used torch.compile with custom flags for some of the more performance-critical functions and used bfloat16 for most things, with a sprinkle of float 32 (I also experimented with some fp8, but was not able to make it work).
I modified my transformer to have a U-Net like structure, where I store the hidden output state from each attention layer for the `layers/2` first blocks and add them to the `layers/2` last blocks in reverse order. I learnt a parameter for deciding how to mix the previous hidden states and the current one.
Surprising findings:
1. Adam …

Add final result for Herman

---

README.md

Aryaman leaderboard

---

README.md

Standard model, increased number of layers and tuned learning rate and batch sizes, increased feedforward dimension as well

Added Sai Konkimalla to leaderboard

---

README.md

Validation Loss: 3.88
https://api.wandb.ai/links/abcisosm/bgl39okf
Description: torch.compile, scaling up the number of total tokens to 1 hr 30 min.

William Huang's Submission

---

README.md

what i did: increased batch size, tuned LR and increased LR range, increased depth of model

kaitlyn's submission

---

README.md

Naive implementation of pre-norm rotary Transformer from assignment with some tweaks:
- muP initialization and LR multipliers
- larger model and context: 512 context, 8 layers, d_model=768, d_ff=2048, n_heads=12, batch size=96, total steps=28000
- bf16 training with grad scaler
- gradient accumulation = 2
- Muon optimizer for 2d params with lr 1.725e-2, lr_min=1.15e-3, wd=1.15e-4, momentum=0.95 with 300 steps warmup 
- cosine lr schedule with warmup steps = 1000
- QK-norm
- LayerNorm-scaling (by block position)
- aux Z-loss with weight 1e-4

Add George Grigorev submission
